name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "SAMEER DAHIYA"
      - name: Print greeting2
        run: echo "hello word"
      - name: Print Good by
        run: echo "DONE- BY SAMEER"

      
